Created subcommand hierarchy
silinternational/tfc-ops pull request #25
Opened 2021-02-01 22:56 UTC by joel29dec

2021-02-02 21:32 UTC, fillup requested changes
Code looks good. I added a few small comments about usage content and a function name. Once those are updated I'll be ready to merge.

2021-02-02 21:32 UTC, fillup commented on README.md
> +  workspaces  Report on workspaces
I suppose both the `variables` and `workspaces` commands are no longer just "reports", so these descriptions can be updated to "Operations and reports related to ___"

2021-02-02 21:32 UTC, fillup commented on README.md
> +  terraform-cloud-ops workspaces [command]
Can we update usage comments to reference the CLI as `tfc-ops` instead of `terraform-cloud-ops`?

2021-02-02 21:32 UTC, fillup commented on cmd/variablesList.go
> +func runVariables() {
Let's rename this to `runVariablesList` to be clearly for the `list` subcommand

2021-02-02 21:43 UTC, Schparky reviewed
looks good!

2021-02-02 21:43 UTC, Schparky commented on cmd/variablesList.go
> +func runVariables() {
Along those lines, the `runUpdateVariables` function should probably be `runVariablesUpdate` for consistency. (In file cmd/VariablesUpdate.go, Github won't allow a comment there.)

2021-02-02 21:56 UTC, Baggerone approved these changes

2021-03-16 18:28 UTC, fillup approved these changes

2021-03-16 18:28 UTC, merged